[INFO 11:18:59] pymarl Running command 'my_main'
[INFO 11:18:59] pymarl Started run with ID "1"
[DEBUG 11:18:59] pymarl Starting Heartbeat
[DEBUG 11:18:59] my_main Started
[INFO 11:18:59] my_main Experiment Parameters:
[INFO 11:18:59] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'dnf_rnn',
    'agent_output_type': 'q',
    'asn_hidden_size': 32,
    'batch_size': 128,
    'batch_size_run': 8,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'core_agent_ratio': 0.7,
    'core_extractor_layer_norm': False,
    'core_extractor_type': 'nn',
    'core_extractor_use_orthogonal': False,
    'core_hidden_dim': 32,
    'cpu_inference': True,
    'critic_lr': 0.0005,
    'double_q': True,
    'enable_parallel_computing': False,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'heuristic_rest': False,
                    'map_name': '2c_vs_64g',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 428891663,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 700000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gain': 0.01,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'label': 'default_label',
    'learner': 'nq_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.001,
    'mac': 'dnf_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'dnf',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimizer': 'adam',
    'per_alpha': 0.6,
    'per_beta': 0.4,
    'q_lambda': False,
    'repeat_id': 1,
    'return_priority': False,
    'rnn_hidden_dim': 64,
    'run': 'default',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'save_model': True,
    'save_model_interval': 2000000,
    'save_replay': False,
    'seed': 428891663,
    't_max': 10050000,
    'target_update_interval': 200,
    'td_lambda': 0.6,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'thread_num': 12,
    'use_cuda': True,
    'use_layer_norm': False,
    'use_orthogonal': False,
    'use_per': False,
    'use_tensorboard': True}

Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-5:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-6:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-7:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
Process Process-8:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 256, in env_worker
    env = env_fn.x()
  File "/workspace/feat_pymarl/workspace/src/envs/__init__.py", line 23, in env_fn
    return env(**kwargs)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 198, in __init__
    map_params = get_map_params(self.map_name)
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/maps/__init__.py", line 10, in get_map_params
    return map_param_registry[map_name]
KeyError: '2c_vs_64g'
