[INFO 16:55:55] pymarl Running command 'my_main'
[INFO 16:55:55] pymarl Started run with ID "1"
[DEBUG 16:55:55] pymarl Starting Heartbeat
[DEBUG 16:55:55] my_main Started
[INFO 16:55:55] my_main Experiment Parameters:
[INFO 16:55:55] my_main 

{   'action_selector': 'epsilon_greedy',
    'agent': 'dnf_rnn',
    'agent_output_type': 'q',
    'asn_hidden_size': 32,
    'batch_size': 64,
    'batch_size_run': 8,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'core_agent_ratio': 0.7,
    'core_extractor_layer_norm': False,
    'core_extractor_type': 'svd',
    'core_extractor_use_orthogonal': False,
    'core_hidden_dim': 32,
    'cpu_inference': True,
    'critic_lr': 0.0005,
    'double_q': True,
    'enable_parallel_computing': False,
    'env': 'sc2',
    'env_args': {   'continuing_episode': False,
                    'debug': False,
                    'difficulty': '7',
                    'game_version': None,
                    'heuristic_ai': False,
                    'heuristic_rest': False,
                    'map_name': '1m',
                    'move_amount': 2,
                    'obs_all_health': True,
                    'obs_instead_of_state': False,
                    'obs_last_action': False,
                    'obs_own_health': True,
                    'obs_pathing_grid': False,
                    'obs_terrain_height': False,
                    'obs_timestep_number': False,
                    'replay_dir': '',
                    'replay_prefix': '',
                    'reward_death_value': 10,
                    'reward_defeat': 0,
                    'reward_negative_scale': 0.5,
                    'reward_only_positive': True,
                    'reward_scale': True,
                    'reward_scale_rate': 20,
                    'reward_sparse': False,
                    'reward_win': 200,
                    'seed': 189877451,
                    'state_last_action': True,
                    'state_timestep_number': False,
                    'step_mul': 8},
    'epsilon_anneal_time': 100000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gain': 0.01,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hypernet_embed': 64,
    'label': 'default_label',
    'learner': 'nq_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.001,
    'mac': 'dnf_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'dnf',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimizer': 'adam',
    'per_alpha': 0.6,
    'per_beta': 0.4,
    'q_lambda': False,
    'repeat_id': 1,
    'return_priority': False,
    'rnn_hidden_dim': 64,
    'run': 'default',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'save_model': True,
    'save_model_interval': 2000000,
    'save_replay': False,
    'seed': 189877451,
    't_max': 1000000,
    'target_update_interval': 200,
    'td_lambda': 0.6,
    'test_greedy': True,
    'test_interval': 10000,
    'test_nepisode': 32,
    'thread_num': 12,
    'use_cuda': True,
    'use_layer_norm': False,
    'use_orthogonal': False,
    'use_per': False,
    'use_tensorboard': True}

{'state_shape': 14, 'obs_shape': 10, 'n_actions': 7, 'n_agents': 1, 'n_enemies': 1, 'episode_limit': 30, 'n_normal_actions': 6, 'n_allies': 0, 'state_ally_feats_size': 4, 'state_enemy_feats_size': 3, 'obs_component': [4, (1, 5), (0, 5), 1], 'state_component': [4, 3, 7], 'map_type': 'marines'}
&&&&&&&&&&&&&&&&&&&&&& dnf_rnn 28.328K
&&&&&&&&&&&&&&&&&&&&&& svd 28.328K
dominators_idx: {}, followers_idx: {} tensor([0.]) tensor([])
 &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&& self.batch_device=cpu
Mixer Size: 
7.073K
[INFO 16:55:58] my_main Beginning training for 1000000 timesteps
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 33843 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-uaw1zve0/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 37557 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-963s67ku/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 42673 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-v69o7s0q/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 34557 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-2he6_8h8/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 39479 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-5fvlemfh/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 35665 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-abwyppnl/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 46321 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-d3n2fbqa/
[INFO 16:55:58] absl Launching SC2: /root/StarCraftII/Versions/Base75689/SC2_x64 -listen 127.0.0.1 -port 44331 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-mcshwfj0/
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:42673/sc2api, attempt: 0, running: True
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:33843/sc2api, attempt: 0, running: True
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 42673 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-v69o7s0q/'
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:46321/sc2api, attempt: 0, running: True
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:37557/sc2api, attempt: 0, running: True
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 33843 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-uaw1zve0/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 46321 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-d3n2fbqa/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 35665 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-abwyppnl/'
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 37557 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-963s67ku/'
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:35665/sc2api, attempt: 0, running: True
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:44331/sc2api, attempt: 0, running: True
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:34557/sc2api, attempt: 0, running: True
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Version: B75689 (SC2.4.10)
Build: Aug 12 2019 17:16:57
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 44331 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-mcshwfj0/'
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 39479 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-5fvlemfh/'
Command Line: '"/root/StarCraftII/Versions/Base75689/SC2_x64" -listen 127.0.0.1 -port 34557 -dataDir /root/StarCraftII/ -tempDir /tmp/sc-2he6_8h8/'
[INFO 16:55:58] absl Connecting to: ws://127.0.0.1:39479/sc2api, attempt: 0, running: True
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Starting up...
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
Startup Phase 1 complete
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:42673/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:46321/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:33843/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:37557/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:35665/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:44331/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:34557/sc2api, attempt: 1, running: True
[INFO 16:55:59] absl Connecting to: ws://127.0.0.1:39479/sc2api, attempt: 1, running: True
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Startup Phase 2 complete
Creating stub renderer...
Listening on: 127.0.0.1:44331
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:35665
Listening on: 127.0.0.1:46321
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:33843
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:37557
Listening on: 127.0.0.1:34557
Startup Phase 3 complete. Ready for commands.
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:39479
Startup Phase 3 complete. Ready for commands.
Listening on: 127.0.0.1:42673
Startup Phase 3 complete. Ready for commands.
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:42673/sc2api, attempt: 2, running: True
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:46321/sc2api, attempt: 2, running: True
ConnectHandler: Request from 127.0.0.1:35404 accepted
ReadyHandler: 127.0.0.1:35404 ready
ConnectHandler: Request from 127.0.0.1:33426 accepted
ReadyHandler: 127.0.0.1:33426 ready
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:33843/sc2api, attempt: 2, running: True
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:37557/sc2api, attempt: 2, running: True
ConnectHandler: Request from 127.0.0.1:58200 accepted
ReadyHandler: 127.0.0.1:58200 ready
ConnectHandler: Request from 127.0.0.1:35218 accepted
ReadyHandler: 127.0.0.1:35218 ready
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:35665/sc2api, attempt: 2, running: True
Process Process-1:
ConnectHandler: Request from 127.0.0.1:38552 accepted
ReadyHandler: 127.0.0.1:38552 ready
Process Process-8:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:44331/sc2api, attempt: 2, running: True
ConnectHandler: Request from 127.0.0.1:53450 accepted
ReadyHandler: 127.0.0.1:53450 ready
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:34557/sc2api, attempt: 2, running: True
Process Process-7:
ConnectHandler: Request from 127.0.0.1:37526 accepted
ReadyHandler: 127.0.0.1:37526 ready
Process Process-2:
Process Process-6:
[INFO 16:56:00] absl Connecting to: ws://127.0.0.1:39479/sc2api, attempt: 2, running: True
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
ConnectHandler: Request from 127.0.0.1:58614 accepted
ReadyHandler: 127.0.0.1:58614 ready
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
Process Process-5:
Process Process-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
Process Process-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
Traceback (most recent call last):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pymarl/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/feat_pymarl/workspace/src/runners/parallel_runner.py", line 278, in env_worker
    env.reset()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 403, in reset
    self._launch()
  File "/workspace/feat_pymarl/workspace/src/envs/smac_v1/official/starcraft2.py", line 332, in _launch
    map_data=self._run_config.map_data(_map.path),
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/pysc2/run_configs/lib.py", line 142, in map_data
    raise ValueError(f"Map {map_name} not found in {self.data_dir}/Maps.")
ValueError: Map SMAC_Maps/1m.SC2Map not found in /root/StarCraftII/Maps.
CloseHandler: 127.0.0.1:33426 disconnected
CloseHandler: 127.0.0.1:35404 disconnected
CloseHandler: 127.0.0.1:35218 disconnected
CloseHandler: 127.0.0.1:53450 disconnected
CloseHandler: 127.0.0.1:58614 disconnected
CloseHandler: 127.0.0.1:37526 disconnected
CloseHandler: 127.0.0.1:38552 disconnected
CloseHandler: 127.0.0.1:58200 disconnected
